/*
 * File: app/model/contacts/Model.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ContactManagerModule.model.contacts.Model', {
    extend: 'Ext.data.Model',
    alias: 'model.contacts.model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'title'
        },
        {
            name: 'first_name'
        },
        {
            name: 'middle_name'
        },
        {
            name: 'last_name'
        },
        {
            name: 'suffix'
        },
        {
            name: 'gender'
        },
        {
            name: 'home_phone'
        },
        {
            name: 'mobile_phone'
        },
        {
            name: 'personal_email'
        },
        {
            name: 'home_street'
        },
        {
            name: 'home_city'
        },
        {
            name: 'home_state'
        },
        {
            name: 'home_postal_code'
        },
        {
            name: 'home_country'
        },
        {
            name: 'company_name'
        },
        {
            name: 'company_phone'
        },
        {
            name: 'company_email'
        },
        {
            name: 'company_street'
        },
        {
            name: 'company_city'
        },
        {
            name: 'company_state'
        },
        {
            name: 'company_postal_code'
        },
        {
            name: 'company_country'
        }
    ]
});