/*
 * File: app/view/import/FileImport.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ContactManagerModule.view.import.FileImport', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.import.fileimport',

    requires: [
        'ContactManagerModule.view.import.FileImportViewModel'
    ],

    viewModel: {
        type: 'import.fileimport'
    },
    title: 'File Import'

});