/*
 * File: app/view/contacts/AddContact.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ContactManagerModule.view.contacts.AddContact', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.contacts.addcontact',

    requires: [
        'ContactManagerModule.view.contacts.AddContactViewModel',
        'Ext.form.Panel',
        'Ext.form.field.Text'
    ],

    viewModel: {
        type: 'contacts.addcontact'
    },
    width: 400,
    title: 'Add New Contact',

    items: [
        {
            xtype: 'form',
            height: 400,
            scrollable: 'true',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Title'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'First Name'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Middle Name'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Last Name*'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Suffix'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Gender'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Home Phone'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Mobile Phone'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Personal Email'
                }
            ]
        }
    ]

});