/*
 * File: app/view/contacts/ContactPanel.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ContactManagerModule.view.contacts.ContactPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.contacts.contactpanel',

    requires: [
        'ContactManagerModule.view.contacts.ContactPanelViewModel',
        'ContactManagerModule.view.contacts.ListPanelNarrow',
        'ContactManagerModule.view.contacts.InfoPanel',
        'Ext.panel.Panel'
    ],

    viewModel: {
        type: 'contacts.contactpanel'
    },

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    dockedItems: [
        {
            xtype: 'contacts.listpanelnarrow',
            flex: 1,
            dock: 'left'
        }
    ],
    items: [
        {
            xtype: 'contacts.infopanel',
            flex: 1
        }
    ]

});