/*
 * File: app/view/contacts/EmptyList.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ContactManagerModule.view.contacts.EmptyList', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.contacts.emptylist',

    requires: [
        'ContactManagerModule.view.contacts.EmptyListViewModel',
        'Ext.panel.Panel',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'contacts.emptylist'
    },
    id: 'emptyList',
    defaultListenerScope: true,

    layout: {
        type: 'vbox',
        align: 'center',
        pack: 'center'
    },
    items: [
        {
            xtype: 'panel',
            flex: 1,
            maxHeight: 114,
            padding: 10,
            layout: {
                type: 'vbox',
                align: 'center',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'button',
                    id: 'addContacts',
                    margin: '0 10 10',
                    width: 125,
                    text: 'Add Contacts',
                    listeners: {
                        click: 'onAddContactsClick'
                    }
                },
                {
                    xtype: 'button',
                    id: 'importContacts',
                    margin: '0 10',
                    width: 125,
                    text: 'Import Contacts',
                    listeners: {
                        click: 'onImportContactsClick'
                    }
                }
            ]
        }
    ],

    onAddContactsClick: function(button, e, eOpts) {
        Ext.getCmp('emptyList').hide();
        Ext.getCmp('addNewContact').show();
    },

    onImportContactsClick: function(button, e, eOpts) {
        Ext.getCmp('emptyList').hide();
        Ext.getCmp('contactsImportPanel').show();
    }

});