/*
 * File: app/view/contacts/FieldMatcher.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ContactManagerModule.view.contacts.FieldMatcher', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.contacts.fieldmatcher',

    requires: [
        'ContactManagerModule.view.contacts.FieldMatcherViewModel',
        'Ext.button.Button',
        'Ext.menu.Menu',
        'Ext.menu.Item'
    ],

    viewModel: {
        type: 'contacts.fieldmatcher'
    },
    frame: true,
    id: 'fieldMatcher',
    width: 520,
    title: 'Import Contacts from .CSV/.XLS file',

    layout: {
        type: 'vbox',
        align: 'center'
    },
    items: [
        {
            xtype: 'panel',
            html: '<p style="font-size: 18px;">Match the file fields to template fields</p>',
            margin: '0 10',
            padding: '0 5'
        },
        {
            xtype: 'panel',
            flex: 1,
            margin: '0 10',
            layout: 'hbox',
            items: [
                {
                    xtype: 'panel',
                    flex: 1,
                    width: 250,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            html: '<p style="font-size: 15px; color: #a0a0a0;">Contact Manager Fields</p>',
                            margin: '0 5'
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            html: '<p style="font-size: 14px;">First Name</p>',
                            margin: '0 5'
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            hidden: true,
                            html: '<p style="font-size: 14px;">Middle Name</p>',
                            margin: '0 5'
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            html: '<p style="font-size: 14px;">Last Name</p>',
                            margin: '0 5'
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            html: '<p style="font-size: 14px;">Title</p>',
                            margin: '0 5'
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            hidden: true,
                            html: '<p style="font-size: 14px;">Suffix</p>',
                            margin: '0 5'
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            hidden: true,
                            html: '<p style="font-size: 14px;">Gender</p>',
                            margin: '0 5'
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            html: '<p style="font-size: 14px;">Company Name</p>',
                            margin: '0 5'
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            html: '<p style="font-size: 14px;">Company Phone</p>',
                            margin: '0 5'
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            html: '<p style="font-size: 14px;">Home Phone</p>',
                            margin: '0 5'
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            html: '<p style="font-size: 14px;">Mobile Phone</p>',
                            margin: '0 5'
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            hidden: true,
                            html: '<p style="font-size: 14px;">Personal Email</p>',
                            margin: '0 5'
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            html: '<p style="font-size: 14px;">Home Street</p>',
                            margin: '0 5'
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            html: '<p style="font-size: 14px;">Home City</p>',
                            margin: '0 5'
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            html: '<p style="font-size: 14px;">Home State</p>',
                            margin: '0 5'
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            html: '<p style="font-size: 14px;">Home Postal Code</p>',
                            margin: '0 5'
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            hidden: true,
                            html: '<p style="font-size: 14px;">Home Country</p>',
                            margin: '0 5'
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            hidden: true,
                            html: '<p style="font-size: 14px;">Company Email</p>',
                            margin: '0 5'
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            hidden: true,
                            html: '<p style="font-size: 14px;">Company Street</p>',
                            margin: '0 5'
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            hidden: true,
                            html: '<p style="font-size: 14px;">Company City</p>',
                            margin: '0 5'
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            hidden: true,
                            html: '<p style="font-size: 14px;">Company Postal Code</p>',
                            margin: '0 5'
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            hidden: true,
                            html: '<p style="font-size: 14px;">Company Country</p>',
                            margin: '0 5'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    width: 250,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            html: '<p style="font-size: 15px; color: #a0a0a0;">Fields in imported file</p>',
                            margin: '0 5'
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            hidden: true,
                            margin: 5,
                            padding: 8.5,
                            text: 'Match to Field',
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            hidden: true,
                            margin: 5,
                            padding: 8.5,
                            text: 'Match to Field',
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            hidden: true,
                            margin: 5,
                            padding: 8.5,
                            text: 'Match to Field',
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            hidden: true,
                            margin: 5,
                            padding: 8.5,
                            text: 'Match to Field',
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            hidden: true,
                            margin: 5,
                            padding: 8.5,
                            text: 'Match to Field',
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            hidden: true,
                            margin: 5,
                            padding: 8.5,
                            text: 'Match to Field',
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            hidden: true,
                            margin: 5,
                            padding: 8.5,
                            text: 'Match to Field',
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            hidden: true,
                            margin: 5,
                            padding: 8.5,
                            text: 'Match to Field',
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            hidden: true,
                            margin: 5,
                            padding: 8.5,
                            text: 'Match to Field',
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            hidden: true,
                            margin: 5,
                            padding: 8.5,
                            text: 'Match to Field',
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            margin: 5,
                            padding: 8.5,
                            text: 'Match to Field',
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            margin: 5,
                            padding: 8.5,
                            text: 'Match to Field',
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            margin: 5,
                            padding: 8.5,
                            text: 'Match to Field',
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            margin: 5,
                            padding: 8.5,
                            text: 'Match to Field',
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            margin: 5,
                            padding: 8.5,
                            text: 'Match to Field',
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            margin: 5,
                            padding: 8.5,
                            text: 'Match to Field',
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            margin: 5,
                            padding: 8.5,
                            text: 'Match to Field',
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            margin: 5,
                            padding: 8.5,
                            text: 'Match to Field',
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            margin: 5,
                            padding: 8.5,
                            text: 'Match to Field',
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            margin: 5,
                            padding: 8.5,
                            text: 'Match to Field',
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            margin: 5,
                            padding: 8.5,
                            text: 'Match to Field',
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    }
                                ]
                            }
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            flex: 1,
            margin: 10,
            padding: 5,
            items: [
                {
                    xtype: 'button',
                    margin: '0 0 0 20',
                    width: 125,
                    text: 'Submit'
                },
                {
                    xtype: 'button',
                    margin: '0 0 0 20',
                    width: 125,
                    text: 'Cancel'
                }
            ]
        }
    ]

});