/*
 * File: app/view/contacts/InfoPanel.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ContactManagerModule.view.contacts.InfoPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.contacts.infopanel',

    requires: [
        'ContactManagerModule.view.contacts.InfoPanelViewModel',
        'Ext.panel.Panel'
    ],

    viewModel: {
        type: 'contacts.infopanel'
    },

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    dockedItems: [
        {
            xtype: 'panel',
            flex: 1,
            dock: 'top',
            height: 57,
            dockedItems: [
                {
                    xtype: 'panel',
                    dock: 'left',
                    html: 'G',
                    margin: 10,
                    padding: 10
                }
            ]
        }
    ]

});