/*
 * File: app/view/contacts/ListPanel.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ContactManagerModule.view.contacts.ListPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.contacts.listpanel',

    requires: [
        'ContactManagerModule.view.contacts.ListPanelViewModel',
        'Ext.button.Button',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Check'
    ],

    viewModel: {
        type: 'contacts.listpanel'
    },
    height: '100%',

    items: [
        {
            xtype: 'button',
            margin: 10,
            width: 125,
            text: 'All Contacts',
            menu: {
                xtype: 'menu',
                width: 120,
                items: [
                    {
                        xtype: 'menuitem',
                        text: 'Menu Item'
                    },
                    {
                        xtype: 'menuitem',
                        text: 'Menu Item'
                    },
                    {
                        xtype: 'menuitem',
                        text: 'Menu Item'
                    }
                ]
            }
        },
        {
            xtype: 'gridpanel',
            frame: true,
            store: 'contacts.Store',
            columns: [
                {
                    xtype: 'checkcolumn',
                    width: 42,
                    headerCheckbox: true
                },
                {
                    xtype: 'gridcolumn',
                    width: 172,
                    dataIndex: 'first_name',
                    text: 'First Name'
                },
                {
                    xtype: 'gridcolumn',
                    width: 198,
                    dataIndex: 'last_name',
                    text: 'Last Name'
                },
                {
                    xtype: 'gridcolumn',
                    width: 282,
                    dataIndex: 'company_name',
                    text: 'Company Name'
                },
                {
                    xtype: 'gridcolumn',
                    width: 320,
                    dataIndex: 'company_email',
                    text: 'Company Email'
                },
                {
                    xtype: 'gridcolumn',
                    width: 292,
                    dataIndex: 'company_phone',
                    text: 'Company Phone'
                }
            ]
        },
        {
            xtype: 'panel',
            items: [
                {
                    xtype: 'button',
                    margin: 10,
                    width: 125,
                    text: '10 per page',
                    menu: {
                        xtype: 'menu',
                        width: 120,
                        items: [
                            {
                                xtype: 'menuitem',
                                text: 'Menu Item'
                            },
                            {
                                xtype: 'menuitem',
                                text: 'Menu Item'
                            },
                            {
                                xtype: 'menuitem',
                                text: 'Menu Item'
                            }
                        ]
                    }
                }
            ]
        }
    ]

});